# Generated by Django 6.1.1 on 2026-09-09 10:48

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', accounts.fields.EncryptedCharField(max_length=500)),
                ('passport_issuing_country', models.CharField(max_length=100)),
                ('passport_expiry', models.DateField()),
                ('student_id_number', models.CharField(max_length=50)),
                ('student_registration_number', models.CharField(blank=True, max_length=50)),
                ('institution_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('level_of_study', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate (Masters)'), ('doctoral', 'Doctoral'), ('exchange', 'Exchange / non-degree')], max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student record',
            },
        ),
    ]
